### PR TITLE
adds basic food table, material icons and milligram framework

### PR DESCRIPTION
**Pull request by cmacaulay**
🎉 
- pretty basic so far (see below)
- took a while to figure out compiling, but got it to work w/ this command: `stylus -w main.styl -o main.css`
- @case-eee wondering what best practices are for asset file structure 

screen shot 2017-05-07 at 9 23 10 pm

### CODE REVIEW

**Comment by TheKaterTot** [comment]
We have some files that I think we might not need. For example, there's an example of an index.html file, but we don't want that in our repo. We also have every version of the stylus css file (.css, .min, .map, .min.map, etc). I'm wondering if we only need one of these; I've been able to delete a lot of the duplication with bootstrap before, but I'm not sure. @case-eee might know, or else I say we just try deleting some and testing

**Comment by cmacaulay** [comment]
@TheKaterTot sure, I just removed them and pushed. we can probably just keep some of the minified versions of the src files, but got rid of most of them for now.

**Comment by case-eee** [comment]
@cmacaulay @TheKaterTot i'd probably just keep the minified version of the files. i don't believe you need all of them (unless something is special with stylus). unfortunately, i don't think there's a **best** practice with file structure. everyone has their (typically very strong) opinions about this. i suggest organizing it in a way that makes sense to y'all. you may want to organize it similarly to the rails asset pipeline to give you some structure

**Comment by case-eee** [comment]
@cmacaulay @TheKaterTot could you also add me to your backend repository for this project. thanks 😄

**Comment by cmacaulay** [comment]
@case-eee if we keep the minified file, it will already have precompiled the stylus. Does it make more sense to keep the src files, compile it (require it) when we compile our own stylesheets, and delete the files that we don't end up using at the end? Or, pull in the minified sheet in the html head? Thanks!

**Comment by case-eee** [comment]
@cmacaulay i think it makes more sense to do option one. i think you want to pull in as few files as possible in the html head. everything you pull in that way is an extra request to the server for that asset!

**Comment by cmacaulay** [comment]
@case-eee thanks! that's what I was leaning towards. Appreciate your guidance!

**Comment by case-eee** [comment]
of course @cmacaulay 👍

**Comment by TheKaterTot** [comment]
Thank you for bringing in the style and prioritizing it. :D

**Pull request merged**
